# Generated by Django 5.2.1 on 2026-06-02 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Photographer', 'Photographer'), ('Editor', 'Editor'), ('Designer', 'Designer'), ('Manager', 'Manager')], max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Camera Purchase', 'Camera Purchase'), ('Lens Purchase', 'Lens Purchase'), ('Staff Salary', 'Staff Salary'), ('Travel Cost', 'Travel Cost'), ('Studio Rent', 'Studio Rent'), ('Electricity', 'Electricity'), ('Other', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=15)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('invoice_type', models.CharField(choices=[('Photography', 'Photography'), ('Album', 'Album'), ('Combined', 'Combined')], default='Photography', max_length=20)),
                ('photography_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('videography_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('drone_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('led_wall_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('crane_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('live_streaming_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('photo_frame_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('travel_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('album_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('album_type', models.CharField(choices=[('Regular Album', 'Regular Album'), ('Premium Album', 'Premium Album'), ('Luxury Album', 'Luxury Album')], max_length=30)),
                ('album_size', models.CharField(default='12x36', max_length=20)),
                ('pages', models.IntegerField(default=30)),
                ('sheets', models.IntegerField(default=15)),
                ('cover_type', models.CharField(default='Regular Leather', max_length=50)),
                ('extra_pages', models.IntegerField(default=0)),
                ('base_price', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10)),
                ('per_page_cost', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('sheet_cost', models.DecimalField(decimal_places=2, default=30.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('design_status', models.CharField(choices=[('Pending', 'Pending'), ('Designing', 'Designing'), ('Completed', 'Completed'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Staff', 'Staff'), ('Customer', 'Customer')], default='Customer', max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
